# Generated by Django 4.2.6 on 2025-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0015_monocard_is_active_monojar_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="monojar",
            name="invested",
            field=models.IntegerField(default=0),
        ),
    ]
